import Link from 'next/link';
import { ArrowRight, CheckCircle2, FileText, LineChart, SearchCheck, Sparkles } from 'lucide-react';
import { Badge, Button, Card } from '@/components/ui';
import { CandidateNav } from '@/components/nav/candidate-nav';

const features = [
  { icon: FileText, title: 'Know what your resume says', text: 'Extract the details from your resume and turn them into a structured talent profile.' },
  { icon: LineChart, title: 'See your strongest signals', text: 'Review skills, ATS compatibility, and focused recommendations for improving your profile.' },
  { icon: SearchCheck, title: 'Find relevant opportunities', text: 'Compare your analyzed profile against open roles and understand your match.' },
];

export default function CandidatePage() {
  return <div className="min-h-screen overflow-hidden bg-background"><div className="relative grid-bg"><div className="orb -left-16 top-12 h-80 w-80 bg-accent" /><CandidateNav /><main className="relative mx-auto max-w-7xl px-5 pb-20 pt-14 sm:px-6 md:pb-28 md:pt-24"><div className="grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><Badge variant="accent" className="px-3 py-1"><Sparkles size={13} className="mr-1.5" />Candidate workspace</Badge><h1 className="mt-6 max-w-3xl text-4xl font-bold leading-[1.1] tracking-tight text-slate-900 sm:text-5xl">Make every application more <span className="text-gradient">informed.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">TalentAI helps you understand the story your resume tells, sharpen your profile, and pursue roles with more context.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/upload"><Button size="lg" className="bg-secondary">Register as a candidate <ArrowRight size={17} /></Button></Link><Link href="/upload"><Button variant="ghost" size="lg">Log in</Button></Link></div><p className="mt-4 text-sm text-slate-600">Start by securely uploading your resume.</p></div><Card className="p-6 sm:p-8" accentTop accentColor="accent"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent-emphasis">Your next steps</p><div className="mt-6 space-y-5">{['Upload your resume', 'Review your talent report', 'Explore matching roles'].map((step, index) => <div key={step} className="flex items-center gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-accent-subtle text-sm font-bold text-accent-emphasis">0{index + 1}</span><span className="font-medium text-slate-700">{step}</span></div>)}</div></Card></div></main></div><section className="mx-auto max-w-7xl px-5 py-20 sm:px-6 md:py-24"><div className="max-w-2xl"><p className="text-sm font-semibold text-accent">Designed for your job search</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-900 md:text-4xl">Clarity from application to opportunity.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{features.map((feature) => <Card key={feature.title} hover className="p-6" accentTop accentColor="secondary"><feature.icon className="text-secondary-emphasis" size={22} /><h3 className="mt-5 text-lg font-semibold text-slate-900">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{feature.text}</p></Card>)}</div><Card className="mt-10 flex flex-col items-start justify-between gap-5 p-7 sm:flex-row sm:items-center" accentLeft accentColor="accent"><div><h2 className="text-xl font-semibold text-slate-900">Ready to see your profile more clearly?</h2><p className="mt-2 text-sm text-slate-600">Upload a resume to begin your candidate workspace.</p></div><Link href="/upload"><Button className="bg-secondary">Register / log in <ArrowRight size={16} /></Button></Link></Card></section></div>;
}
